/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hjs_zhi_com_ndk_JNI */

#ifndef _Included_hjs_zhi_com_ndk_JNI
#define _Included_hjs_zhi_com_ndk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hjs_zhi_com_ndk_JNI
 * Method:    intcreaseArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_hjs_zhi_com_ndk_JNI_intcreaseArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     hjs_zhi_com_ndk_JNI
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hjs_zhi_com_ndk_JNI_checkPwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
