/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hjs_zhi_com_ndk_JniUtils */

#ifndef _Included_hjs_zhi_com_ndk_JniUtils
#define _Included_hjs_zhi_com_ndk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hjs_zhi_com_ndk_JniUtils
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hjs_zhi_com_ndk_JniUtils_helloFromC
  (JNIEnv *, jclass);

/*
 * Class:     hjs_zhi_com_ndk_JniUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hjs_zhi_com_ndk_JniUtils_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hjs_zhi_com_ndk_JniUtils
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hjs_zhi_com_ndk_JniUtils_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
