/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hjs_zhi_com_ndk_JniUtils */

#ifndef _Included_hjs_zhi_com_ndk_JniUtils
#define _Included_hjs_zhi_com_ndk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hjs_zhi_com_ndk_JniUtils
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hjs_zhi_com_ndk_JniUtils_helloFromC
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
